services:
  tictactoe:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tictactoe;Username=postgres;Password=1234567890
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tictactoe-network


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: tictactoe
    ports:
      - "5432:5432"
    networks:
      - tictactoe-network
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
volumes:
  postgres_data:

networks:
  tictactoe-network: