name: .NET Tests

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

env:
  ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=tictactoe;Username=postgres;Password=1234567890"

jobs:
  test-on-all-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # macos-latest можно добавить, если требуется
    runs-on: ${{ matrix.os }}
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234567890
          POSTGRES_DB: tictactoe
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Wait for PostgreSQL to be ready
      run: sleep 5

    - name: Run EF Core migrations
      run: dotnet ef database update --project TicTacToe --verbose

    - name: Test
      run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed"
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}
        path: "**/TestResults/*.trx"
