name: .NET Tests with PostgreSQL

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

env:
  ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=tictactoe;Username=postgres;Password=1234567890"
  ASPNETCORE_ENVIRONMENT: "Test"

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234567890
          POSTGRES_DB: tictactoe
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Install EF Core CLI tools
      run: dotnet tool install --global dotnet-ef

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready!"
            exit 0
          fi
          sleep 2
        done
        echo "PostgreSQL failed to start"
        exit 1

    - name: Run EF Core migrations
      run: dotnet ef database update --project TicTacToe --verbose

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed" --results-directory TestResults
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/**/*
        retention-days: 1
